package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.Apps;
import me.anchora.inpaasmgr.entry.ccdb.AppsCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(AppsCriteria example);
    int countWithMany(Apps condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(AppsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(Apps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(Apps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<Apps> selectByExampleWithRowbounds(AppsCriteria example, RowBounds rowBounds);
    List<Apps> selectWithMany(Apps condition, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<Apps> selectByExample(AppsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    Apps selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") Apps record, @Param("example") AppsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") Apps record, @Param("example") AppsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKeySelective(Apps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apps
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKey(Apps record);
    
    int queryMem();
    
    List<Apps> queryForWithoutAccess(List<String> list);
    
    List<Apps> queryAppsByAppIds(List<String> list);
}