package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;

import me.anchora.inpaasmgr.entry.CommonVo;
import me.anchora.inpaasmgr.entry.ccdb.CcUsers;
import me.anchora.inpaasmgr.entry.ccdb.CcUsersCriteria;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CcUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(CcUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(CcUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(CcUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(CcUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<CcUsers> selectByExampleWithRowbounds(CcUsersCriteria example, RowBounds rowBounds);
    List<CommonVo> selectWithOrgSpace(CommonVo commonVo, RowBounds rowBounds);
    int countWithOrgSpace(CommonVo commonVo);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<CcUsers> selectByExample(CcUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    CcUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") CcUsers record, @Param("example") CcUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") CcUsers record, @Param("example") CcUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKeySelective(CcUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKey(CcUsers record);
}