package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.DomainsOrganizations;
import me.anchora.inpaasmgr.entry.ccdb.DomainsOrganizationsCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DomainsOrganizationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains_organizations
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(DomainsOrganizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains_organizations
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(DomainsOrganizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains_organizations
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(DomainsOrganizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains_organizations
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(DomainsOrganizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains_organizations
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<DomainsOrganizations> selectByExampleWithRowbounds(DomainsOrganizationsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains_organizations
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<DomainsOrganizations> selectByExample(DomainsOrganizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains_organizations
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") DomainsOrganizations record, @Param("example") DomainsOrganizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains_organizations
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") DomainsOrganizations record, @Param("example") DomainsOrganizationsCriteria example);
}