package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.Domains;
import me.anchora.inpaasmgr.entry.ccdb.DomainsCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DomainsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(DomainsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(DomainsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(Domains record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(Domains record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<Domains> selectByExampleWithRowbounds(DomainsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<Domains> selectByExample(DomainsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    Domains selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") Domains record, @Param("example") DomainsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") Domains record, @Param("example") DomainsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKeySelective(Domains record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKey(Domains record);
}