package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.OrganizationsManagers;
import me.anchora.inpaasmgr.entry.ccdb.OrganizationsManagersCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrganizationsManagersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(OrganizationsManagersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(OrganizationsManagersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(OrganizationsManagers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(OrganizationsManagers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<OrganizationsManagers> selectByExampleWithRowbounds(OrganizationsManagersCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<OrganizationsManagers> selectByExample(OrganizationsManagersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") OrganizationsManagers record, @Param("example") OrganizationsManagersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") OrganizationsManagers record, @Param("example") OrganizationsManagersCriteria example);
}