package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.Organizations;
import me.anchora.inpaasmgr.entry.ccdb.OrganizationsCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrganizationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int countByExample(OrganizationsCriteria example);
    int countWithQuota(Organizations condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int deleteByExample(OrganizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int insert(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int insertSelective(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    List<Organizations> selectByExampleWithRowbounds(OrganizationsCriteria example, RowBounds rowBounds);
    
    List<Organizations> selectWithQuotaWithRowbounds(Organizations condition, RowBounds rowBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    List<Organizations> selectByExample(OrganizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    Organizations selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") Organizations record, @Param("example") OrganizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int updateByExample(@Param("record") Organizations record, @Param("example") OrganizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int updateByPrimaryKeySelective(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    int updateByPrimaryKey(Organizations record);
}