package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.OrganizationsUsers;
import me.anchora.inpaasmgr.entry.ccdb.OrganizationsUsersCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrganizationsUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(OrganizationsUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(OrganizationsUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(OrganizationsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(OrganizationsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<OrganizationsUsers> selectByExampleWithRowbounds(OrganizationsUsersCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<OrganizationsUsers> selectByExample(OrganizationsUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") OrganizationsUsers record, @Param("example") OrganizationsUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations_users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") OrganizationsUsers record, @Param("example") OrganizationsUsersCriteria example);
}