package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;

import me.anchora.inpaasmgr.entry.ccdb.Spaces;
import me.anchora.inpaasmgr.entry.ccdb.SpacesCriteria;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SpacesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(SpacesCriteria example);
    int countWithOrg(Spaces spaces);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(SpacesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(Spaces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(Spaces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<Spaces> selectByExampleWithRowbounds(SpacesCriteria example, RowBounds rowBounds);
   
    List<Spaces> selectWithOrganizationByExampleWithRowbounds(Spaces example, RowBounds rowBounds);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<Spaces> selectByExample(SpacesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    Spaces selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") Spaces record, @Param("example") SpacesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") Spaces record, @Param("example") SpacesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKeySelective(Spaces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKey(Spaces record);
}