package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.SpacesManagers;
import me.anchora.inpaasmgr.entry.ccdb.SpacesManagersCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SpacesManagersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(SpacesManagersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(SpacesManagersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(SpacesManagers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(SpacesManagers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<SpacesManagers> selectByExampleWithRowbounds(SpacesManagersCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<SpacesManagers> selectByExample(SpacesManagersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") SpacesManagers record, @Param("example") SpacesManagersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_managers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") SpacesManagers record, @Param("example") SpacesManagersCriteria example);
}