package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.SpacesDevelopers;
import me.anchora.inpaasmgr.entry.ccdb.SpacesDevelopersCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SpacesDevelopersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_developers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(SpacesDevelopersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_developers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(SpacesDevelopersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_developers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(SpacesDevelopers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_developers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(SpacesDevelopers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_developers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<SpacesDevelopers> selectByExampleWithRowbounds(SpacesDevelopersCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_developers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<SpacesDevelopers> selectByExample(SpacesDevelopersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_developers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") SpacesDevelopers record, @Param("example") SpacesDevelopersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spaces_developers
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") SpacesDevelopers record, @Param("example") SpacesDevelopersCriteria example);
}