package me.anchora.inpaasmgr.dao.ccdb;

import java.util.List;
import me.anchora.inpaasmgr.entry.ccdb.Stacks;
import me.anchora.inpaasmgr.entry.ccdb.StacksCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StacksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int countByExample(StacksCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByExample(StacksCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insert(Stacks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int insertSelective(Stacks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<Stacks> selectByExampleWithRowbounds(StacksCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    List<Stacks> selectByExample(StacksCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    Stacks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") Stacks record, @Param("example") StacksCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByExample(@Param("record") Stacks record, @Param("example") StacksCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKeySelective(Stacks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    int updateByPrimaryKey(Stacks record);
}