package me.anchora.inpaasmgr.entry.ccdb;

import java.io.Serializable;
import java.util.Date;
import me.anchora.inpaasmgr.entry.base.PageEntry;

public class Domains extends PageEntry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.domains.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.domains.guid
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.domains.created_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.domains.updated_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.domains.name
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Object name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.domains.wildcard
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Boolean wildcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.domains.owning_organization_id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Integer owningOrganizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.domains.id
     *
     * @return the value of public.domains.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.domains.id
     *
     * @param id the value for public.domains.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.domains.guid
     *
     * @return the value of public.domains.guid
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.domains.guid
     *
     * @param guid the value for public.domains.guid
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.domains.created_at
     *
     * @return the value of public.domains.created_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.domains.created_at
     *
     * @param createdAt the value for public.domains.created_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.domains.updated_at
     *
     * @return the value of public.domains.updated_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.domains.updated_at
     *
     * @param updatedAt the value for public.domains.updated_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.domains.name
     *
     * @return the value of public.domains.name
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Object getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.domains.name
     *
     * @param name the value for public.domains.name
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setName(Object name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.domains.wildcard
     *
     * @return the value of public.domains.wildcard
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Boolean getWildcard() {
        return wildcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.domains.wildcard
     *
     * @param wildcard the value for public.domains.wildcard
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setWildcard(Boolean wildcard) {
        this.wildcard = wildcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.domains.owning_organization_id
     *
     * @return the value of public.domains.owning_organization_id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Integer getOwningOrganizationId() {
        return owningOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.domains.owning_organization_id
     *
     * @param owningOrganizationId the value for public.domains.owning_organization_id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setOwningOrganizationId(Integer owningOrganizationId) {
        this.owningOrganizationId = owningOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.domains
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", guid=").append(guid);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", name=").append(name);
        sb.append(", wildcard=").append(wildcard);
        sb.append(", owningOrganizationId=").append(owningOrganizationId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}