package me.anchora.inpaasmgr.entry.ccdb;

import java.io.Serializable;
import java.util.Date;
import me.anchora.inpaasmgr.entry.base.SuperQuotaDefinitions;

public class Organizations extends SuperQuotaDefinitions implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.organizations.id
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.organizations.guid
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.organizations.created_at
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.organizations.updated_at
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.organizations.name
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private Object name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.organizations.billing_enabled
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private Boolean billingEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.organizations.quota_definition_id
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private Integer quotaDefinitionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.organizations.status
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.organizations.id
     *
     * @return the value of public.organizations.id
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.organizations.id
     *
     * @param id the value for public.organizations.id
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.organizations.guid
     *
     * @return the value of public.organizations.guid
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.organizations.guid
     *
     * @param guid the value for public.organizations.guid
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.organizations.created_at
     *
     * @return the value of public.organizations.created_at
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.organizations.created_at
     *
     * @param createdAt the value for public.organizations.created_at
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.organizations.updated_at
     *
     * @return the value of public.organizations.updated_at
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.organizations.updated_at
     *
     * @param updatedAt the value for public.organizations.updated_at
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.organizations.name
     *
     * @return the value of public.organizations.name
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public Object getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.organizations.name
     *
     * @param name the value for public.organizations.name
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public void setName(Object name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.organizations.billing_enabled
     *
     * @return the value of public.organizations.billing_enabled
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public Boolean getBillingEnabled() {
        return billingEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.organizations.billing_enabled
     *
     * @param billingEnabled the value for public.organizations.billing_enabled
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public void setBillingEnabled(Boolean billingEnabled) {
        this.billingEnabled = billingEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.organizations.quota_definition_id
     *
     * @return the value of public.organizations.quota_definition_id
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public Integer getQuotaDefinitionId() {
        return quotaDefinitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.organizations.quota_definition_id
     *
     * @param quotaDefinitionId the value for public.organizations.quota_definition_id
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public void setQuotaDefinitionId(Integer quotaDefinitionId) {
        this.quotaDefinitionId = quotaDefinitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.organizations.status
     *
     * @return the value of public.organizations.status
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.organizations.status
     *
     * @param status the value for public.organizations.status
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.organizations
     *
     * @mbggenerated Wed Mar 19 12:20:55 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", guid=").append(guid);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", name=").append(name);
        sb.append(", billingEnabled=").append(billingEnabled);
        sb.append(", quotaDefinitionId=").append(quotaDefinitionId);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}