package me.anchora.inpaasmgr.entry.ccdb;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuotaDefinitionsCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public QuotaDefinitionsCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("guid is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("guid is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("guid =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("guid <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("guid >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("guid >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("guid <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("guid <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("guid like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("guid not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("guid in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("guid not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("guid between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("guid not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(Object value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(Object value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(Object value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(Object value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(Object value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(Object value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<Object> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<Object> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(Object value1, Object value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(Object value1, Object value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedIsNull() {
            addCriterion("non_basic_services_allowed is null");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedIsNotNull() {
            addCriterion("non_basic_services_allowed is not null");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedEqualTo(Boolean value) {
            addCriterion("non_basic_services_allowed =", value, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedNotEqualTo(Boolean value) {
            addCriterion("non_basic_services_allowed <>", value, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedGreaterThan(Boolean value) {
            addCriterion("non_basic_services_allowed >", value, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("non_basic_services_allowed >=", value, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedLessThan(Boolean value) {
            addCriterion("non_basic_services_allowed <", value, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedLessThanOrEqualTo(Boolean value) {
            addCriterion("non_basic_services_allowed <=", value, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedIn(List<Boolean> values) {
            addCriterion("non_basic_services_allowed in", values, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedNotIn(List<Boolean> values) {
            addCriterion("non_basic_services_allowed not in", values, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedBetween(Boolean value1, Boolean value2) {
            addCriterion("non_basic_services_allowed between", value1, value2, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andNonBasicServicesAllowedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("non_basic_services_allowed not between", value1, value2, "nonBasicServicesAllowed");
            return (Criteria) this;
        }

        public Criteria andTotalServicesIsNull() {
            addCriterion("total_services is null");
            return (Criteria) this;
        }

        public Criteria andTotalServicesIsNotNull() {
            addCriterion("total_services is not null");
            return (Criteria) this;
        }

        public Criteria andTotalServicesEqualTo(Integer value) {
            addCriterion("total_services =", value, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesNotEqualTo(Integer value) {
            addCriterion("total_services <>", value, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesGreaterThan(Integer value) {
            addCriterion("total_services >", value, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_services >=", value, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesLessThan(Integer value) {
            addCriterion("total_services <", value, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesLessThanOrEqualTo(Integer value) {
            addCriterion("total_services <=", value, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesIn(List<Integer> values) {
            addCriterion("total_services in", values, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesNotIn(List<Integer> values) {
            addCriterion("total_services not in", values, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesBetween(Integer value1, Integer value2) {
            addCriterion("total_services between", value1, value2, "totalServices");
            return (Criteria) this;
        }

        public Criteria andTotalServicesNotBetween(Integer value1, Integer value2) {
            addCriterion("total_services not between", value1, value2, "totalServices");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitIsNull() {
            addCriterion("memory_limit is null");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitIsNotNull() {
            addCriterion("memory_limit is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitEqualTo(Integer value) {
            addCriterion("memory_limit =", value, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitNotEqualTo(Integer value) {
            addCriterion("memory_limit <>", value, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitGreaterThan(Integer value) {
            addCriterion("memory_limit >", value, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("memory_limit >=", value, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitLessThan(Integer value) {
            addCriterion("memory_limit <", value, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitLessThanOrEqualTo(Integer value) {
            addCriterion("memory_limit <=", value, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitIn(List<Integer> values) {
            addCriterion("memory_limit in", values, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitNotIn(List<Integer> values) {
            addCriterion("memory_limit not in", values, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitBetween(Integer value1, Integer value2) {
            addCriterion("memory_limit between", value1, value2, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andMemoryLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("memory_limit not between", value1, value2, "memoryLimit");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesIsNull() {
            addCriterion("total_routes is null");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesIsNotNull() {
            addCriterion("total_routes is not null");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesEqualTo(Integer value) {
            addCriterion("total_routes =", value, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesNotEqualTo(Integer value) {
            addCriterion("total_routes <>", value, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesGreaterThan(Integer value) {
            addCriterion("total_routes >", value, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_routes >=", value, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesLessThan(Integer value) {
            addCriterion("total_routes <", value, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesLessThanOrEqualTo(Integer value) {
            addCriterion("total_routes <=", value, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesIn(List<Integer> values) {
            addCriterion("total_routes in", values, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesNotIn(List<Integer> values) {
            addCriterion("total_routes not in", values, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesBetween(Integer value1, Integer value2) {
            addCriterion("total_routes between", value1, value2, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andTotalRoutesNotBetween(Integer value1, Integer value2) {
            addCriterion("total_routes not between", value1, value2, "totalRoutes");
            return (Criteria) this;
        }

        public Criteria andGuidLikeInsensitive(String value) {
            addCriterion("upper(guid) like", value.toUpperCase(), "guid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.quota_definitions
     *
     * @mbggenerated do_not_delete_during_merge Tue May 27 10:15:59 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.quota_definitions
     *
     * @mbggenerated Tue May 27 10:15:59 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}