package me.anchora.inpaasmgr.entry.ccdb;

import java.io.Serializable;
import java.util.Date;
import me.anchora.inpaasmgr.entry.base.PageEntry;

public class Stacks extends PageEntry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stacks.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stacks.guid
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stacks.created_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stacks.updated_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stacks.name
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stacks.description
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stacks.id
     *
     * @return the value of public.stacks.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stacks.id
     *
     * @param id the value for public.stacks.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stacks.guid
     *
     * @return the value of public.stacks.guid
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stacks.guid
     *
     * @param guid the value for public.stacks.guid
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stacks.created_at
     *
     * @return the value of public.stacks.created_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stacks.created_at
     *
     * @param createdAt the value for public.stacks.created_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stacks.updated_at
     *
     * @return the value of public.stacks.updated_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stacks.updated_at
     *
     * @param updatedAt the value for public.stacks.updated_at
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stacks.name
     *
     * @return the value of public.stacks.name
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stacks.name
     *
     * @param name the value for public.stacks.name
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stacks.description
     *
     * @return the value of public.stacks.description
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stacks.description
     *
     * @param description the value for public.stacks.description
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stacks
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", guid=").append(guid);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}