package me.anchora.inpaasmgr.entry.inpaas;

import java.io.Serializable;
import java.util.Date;
import me.anchora.inpaasmgr.entry.base.PageEntry;

public class PaasUsers extends PageEntry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_email
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_pwd
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_cf_pwd
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userCfPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_platform
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.quota_id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private Long quotaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.last_login_ip
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.current_login_ip
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String currentLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_phone
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.phone_identified
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String phoneIdentified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_identified
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userIdentified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_active
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_from
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_type
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.parent_id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.contacts_name
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String contactsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.contacts_id_no
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String contactsIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.contacts_id_img1
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String contactsIdImg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.contacts_id_img2
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String contactsIdImg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.contacts_addr
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String contactsAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.company_name
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.company_bussiness_license
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String companyBussinessLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.company_bussiness_license_img
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String companyBussinessLicenseImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.company_position
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String companyPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.company_department
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String companyDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.company_org_code
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String companyOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.user_relevant
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String userRelevant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.remark
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.accesskey
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String accesskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.secretkey
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private String secretkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.created_at
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_users.updated_at
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.id
     *
     * @return the value of paas_users.id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.id
     *
     * @param id the value for paas_users.id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_email
     *
     * @return the value of paas_users.user_email
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_email
     *
     * @param userEmail the value for paas_users.user_email
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_pwd
     *
     * @return the value of paas_users.user_pwd
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_pwd
     *
     * @param userPwd the value for paas_users.user_pwd
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_cf_pwd
     *
     * @return the value of paas_users.user_cf_pwd
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserCfPwd() {
        return userCfPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_cf_pwd
     *
     * @param userCfPwd the value for paas_users.user_cf_pwd
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserCfPwd(String userCfPwd) {
        this.userCfPwd = userCfPwd == null ? null : userCfPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_platform
     *
     * @return the value of paas_users.user_platform
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserPlatform() {
        return userPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_platform
     *
     * @param userPlatform the value for paas_users.user_platform
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserPlatform(String userPlatform) {
        this.userPlatform = userPlatform == null ? null : userPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.quota_id
     *
     * @return the value of paas_users.quota_id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public Long getQuotaId() {
        return quotaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.quota_id
     *
     * @param quotaId the value for paas_users.quota_id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setQuotaId(Long quotaId) {
        this.quotaId = quotaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.last_login_ip
     *
     * @return the value of paas_users.last_login_ip
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.last_login_ip
     *
     * @param lastLoginIp the value for paas_users.last_login_ip
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.current_login_ip
     *
     * @return the value of paas_users.current_login_ip
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getCurrentLoginIp() {
        return currentLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.current_login_ip
     *
     * @param currentLoginIp the value for paas_users.current_login_ip
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setCurrentLoginIp(String currentLoginIp) {
        this.currentLoginIp = currentLoginIp == null ? null : currentLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_phone
     *
     * @return the value of paas_users.user_phone
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_phone
     *
     * @param userPhone the value for paas_users.user_phone
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.phone_identified
     *
     * @return the value of paas_users.phone_identified
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getPhoneIdentified() {
        return phoneIdentified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.phone_identified
     *
     * @param phoneIdentified the value for paas_users.phone_identified
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setPhoneIdentified(String phoneIdentified) {
        this.phoneIdentified = phoneIdentified == null ? null : phoneIdentified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_identified
     *
     * @return the value of paas_users.user_identified
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserIdentified() {
        return userIdentified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_identified
     *
     * @param userIdentified the value for paas_users.user_identified
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserIdentified(String userIdentified) {
        this.userIdentified = userIdentified == null ? null : userIdentified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_active
     *
     * @return the value of paas_users.user_active
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserActive() {
        return userActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_active
     *
     * @param userActive the value for paas_users.user_active
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserActive(String userActive) {
        this.userActive = userActive == null ? null : userActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_from
     *
     * @return the value of paas_users.user_from
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserFrom() {
        return userFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_from
     *
     * @param userFrom the value for paas_users.user_from
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserFrom(String userFrom) {
        this.userFrom = userFrom == null ? null : userFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_type
     *
     * @return the value of paas_users.user_type
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_type
     *
     * @param userType the value for paas_users.user_type
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.parent_id
     *
     * @return the value of paas_users.parent_id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.parent_id
     *
     * @param parentId the value for paas_users.parent_id
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.contacts_name
     *
     * @return the value of paas_users.contacts_name
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.contacts_name
     *
     * @param contactsName the value for paas_users.contacts_name
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName == null ? null : contactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.contacts_id_no
     *
     * @return the value of paas_users.contacts_id_no
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getContactsIdNo() {
        return contactsIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.contacts_id_no
     *
     * @param contactsIdNo the value for paas_users.contacts_id_no
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setContactsIdNo(String contactsIdNo) {
        this.contactsIdNo = contactsIdNo == null ? null : contactsIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.contacts_id_img1
     *
     * @return the value of paas_users.contacts_id_img1
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getContactsIdImg1() {
        return contactsIdImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.contacts_id_img1
     *
     * @param contactsIdImg1 the value for paas_users.contacts_id_img1
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setContactsIdImg1(String contactsIdImg1) {
        this.contactsIdImg1 = contactsIdImg1 == null ? null : contactsIdImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.contacts_id_img2
     *
     * @return the value of paas_users.contacts_id_img2
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getContactsIdImg2() {
        return contactsIdImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.contacts_id_img2
     *
     * @param contactsIdImg2 the value for paas_users.contacts_id_img2
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setContactsIdImg2(String contactsIdImg2) {
        this.contactsIdImg2 = contactsIdImg2 == null ? null : contactsIdImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.contacts_addr
     *
     * @return the value of paas_users.contacts_addr
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getContactsAddr() {
        return contactsAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.contacts_addr
     *
     * @param contactsAddr the value for paas_users.contacts_addr
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setContactsAddr(String contactsAddr) {
        this.contactsAddr = contactsAddr == null ? null : contactsAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.company_name
     *
     * @return the value of paas_users.company_name
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.company_name
     *
     * @param companyName the value for paas_users.company_name
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.company_bussiness_license
     *
     * @return the value of paas_users.company_bussiness_license
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getCompanyBussinessLicense() {
        return companyBussinessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.company_bussiness_license
     *
     * @param companyBussinessLicense the value for paas_users.company_bussiness_license
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setCompanyBussinessLicense(String companyBussinessLicense) {
        this.companyBussinessLicense = companyBussinessLicense == null ? null : companyBussinessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.company_bussiness_license_img
     *
     * @return the value of paas_users.company_bussiness_license_img
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getCompanyBussinessLicenseImg() {
        return companyBussinessLicenseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.company_bussiness_license_img
     *
     * @param companyBussinessLicenseImg the value for paas_users.company_bussiness_license_img
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setCompanyBussinessLicenseImg(String companyBussinessLicenseImg) {
        this.companyBussinessLicenseImg = companyBussinessLicenseImg == null ? null : companyBussinessLicenseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.company_position
     *
     * @return the value of paas_users.company_position
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getCompanyPosition() {
        return companyPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.company_position
     *
     * @param companyPosition the value for paas_users.company_position
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setCompanyPosition(String companyPosition) {
        this.companyPosition = companyPosition == null ? null : companyPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.company_department
     *
     * @return the value of paas_users.company_department
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getCompanyDepartment() {
        return companyDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.company_department
     *
     * @param companyDepartment the value for paas_users.company_department
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setCompanyDepartment(String companyDepartment) {
        this.companyDepartment = companyDepartment == null ? null : companyDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.company_org_code
     *
     * @return the value of paas_users.company_org_code
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getCompanyOrgCode() {
        return companyOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.company_org_code
     *
     * @param companyOrgCode the value for paas_users.company_org_code
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setCompanyOrgCode(String companyOrgCode) {
        this.companyOrgCode = companyOrgCode == null ? null : companyOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.user_relevant
     *
     * @return the value of paas_users.user_relevant
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getUserRelevant() {
        return userRelevant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.user_relevant
     *
     * @param userRelevant the value for paas_users.user_relevant
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUserRelevant(String userRelevant) {
        this.userRelevant = userRelevant == null ? null : userRelevant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.remark
     *
     * @return the value of paas_users.remark
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.remark
     *
     * @param remark the value for paas_users.remark
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.accesskey
     *
     * @return the value of paas_users.accesskey
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getAccesskey() {
        return accesskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.accesskey
     *
     * @param accesskey the value for paas_users.accesskey
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setAccesskey(String accesskey) {
        this.accesskey = accesskey == null ? null : accesskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.secretkey
     *
     * @return the value of paas_users.secretkey
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.secretkey
     *
     * @param secretkey the value for paas_users.secretkey
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey == null ? null : secretkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.created_at
     *
     * @return the value of paas_users.created_at
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.created_at
     *
     * @param createdAt the value for paas_users.created_at
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paas_users.updated_at
     *
     * @return the value of paas_users.updated_at
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paas_users.updated_at
     *
     * @param updatedAt the value for paas_users.updated_at
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userPwd=").append(userPwd);
        sb.append(", userCfPwd=").append(userCfPwd);
        sb.append(", userPlatform=").append(userPlatform);
        sb.append(", quotaId=").append(quotaId);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", currentLoginIp=").append(currentLoginIp);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", phoneIdentified=").append(phoneIdentified);
        sb.append(", userIdentified=").append(userIdentified);
        sb.append(", userActive=").append(userActive);
        sb.append(", userFrom=").append(userFrom);
        sb.append(", userType=").append(userType);
        sb.append(", parentId=").append(parentId);
        sb.append(", contactsName=").append(contactsName);
        sb.append(", contactsIdNo=").append(contactsIdNo);
        sb.append(", contactsIdImg1=").append(contactsIdImg1);
        sb.append(", contactsIdImg2=").append(contactsIdImg2);
        sb.append(", contactsAddr=").append(contactsAddr);
        sb.append(", companyName=").append(companyName);
        sb.append(", companyBussinessLicense=").append(companyBussinessLicense);
        sb.append(", companyBussinessLicenseImg=").append(companyBussinessLicenseImg);
        sb.append(", companyPosition=").append(companyPosition);
        sb.append(", companyDepartment=").append(companyDepartment);
        sb.append(", companyOrgCode=").append(companyOrgCode);
        sb.append(", userRelevant=").append(userRelevant);
        sb.append(", remark=").append(remark);
        sb.append(", accesskey=").append(accesskey);
        sb.append(", secretkey=").append(secretkey);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}