package me.anchora.inpaasmgr.dao.inpaasmgr;

import java.util.List;
import me.anchora.inpaasmgr.entry.inpaasmgr.AppMonitDatas;
import me.anchora.inpaasmgr.entry.inpaasmgr.AppMonitDatasCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppMonitDatasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int countByExample(AppMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int deleteByExample(AppMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int insert(AppMonitDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int insertSelective(AppMonitDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    List<AppMonitDatas> selectByExampleWithRowbounds(AppMonitDatasCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    List<AppMonitDatas> selectByExample(AppMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    AppMonitDatas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") AppMonitDatas record, @Param("example") AppMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int updateByExample(@Param("record") AppMonitDatas record, @Param("example") AppMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int updateByPrimaryKeySelective(AppMonitDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_monit_datas
     *
     * @mbggenerated Wed Dec 24 15:19:21 CST 2014
     */
    int updateByPrimaryKey(AppMonitDatas record);

	void insertList(List<AppMonitDatas> dataList);

	void createTable();
}