package me.anchora.inpaasmgr.dao.inpaasmgr;

import java.util.List;
import me.anchora.inpaasmgr.entry.inpaasmgr.CfMonitDatas;
import me.anchora.inpaasmgr.entry.inpaasmgr.CfMonitDatasCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CfMonitDatasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int countByExample(CfMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int deleteByExample(CfMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int insert(CfMonitDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int insertSelective(CfMonitDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    List<CfMonitDatas> selectByExampleWithRowbounds(CfMonitDatasCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    List<CfMonitDatas> selectByExample(CfMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    CfMonitDatas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") CfMonitDatas record, @Param("example") CfMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int updateByExample(@Param("record") CfMonitDatas record, @Param("example") CfMonitDatasCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int updateByPrimaryKeySelective(CfMonitDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    int updateByPrimaryKey(CfMonitDatas record);

	void insertList(List<CfMonitDatas> list);

	void createTable();
}