package me.anchora.inpaasmgr.dao.inpaasmgr;

import java.util.List;
import me.anchora.inpaasmgr.entry.inpaasmgr.MenuLanguages;
import me.anchora.inpaasmgr.entry.inpaasmgr.MenuLanguagesCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MenuLanguagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int countByExample(MenuLanguagesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int deleteByExample(MenuLanguagesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int insert(MenuLanguages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int insertSelective(MenuLanguages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    List<MenuLanguages> selectByExampleWithRowbounds(MenuLanguagesCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    List<MenuLanguages> selectByExample(MenuLanguagesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    MenuLanguages selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") MenuLanguages record, @Param("example") MenuLanguagesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByExample(@Param("record") MenuLanguages record, @Param("example") MenuLanguagesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByPrimaryKeySelective(MenuLanguages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_languages
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByPrimaryKey(MenuLanguages record);
}