package me.anchora.inpaasmgr.dao.inpaasmgr;

import java.util.List;
import me.anchora.inpaasmgr.entry.inpaasmgr.RoleUsers;
import me.anchora.inpaasmgr.entry.inpaasmgr.RoleUsersCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RoleUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int countByExample(RoleUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int deleteByExample(RoleUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int insert(RoleUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int insertSelective(RoleUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    List<RoleUsers> selectByExampleWithRowbounds(RoleUsersCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    List<RoleUsers> selectByExample(RoleUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    RoleUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") RoleUsers record, @Param("example") RoleUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByExample(@Param("record") RoleUsers record, @Param("example") RoleUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByPrimaryKeySelective(RoleUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_users
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByPrimaryKey(RoleUsers record);

	List<RoleUsers> selectByExampleWithOtherWithRowbounds(RoleUsers roleUsers,
			RowBounds rowBounds);

	Integer countByExampleWithOther(RoleUsers roleUsers);
}