package me.anchora.inpaasmgr.dao.inpaasmgr;

import java.util.List;
import me.anchora.inpaasmgr.entry.inpaasmgr.SystemConfig;
import me.anchora.inpaasmgr.entry.inpaasmgr.SystemConfigCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SystemConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int countByExample(SystemConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int deleteByExample(SystemConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int insert(SystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int insertSelective(SystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    List<SystemConfig> selectByExampleWithRowbounds(SystemConfigCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    List<SystemConfig> selectByExample(SystemConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    SystemConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") SystemConfig record, @Param("example") SystemConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int updateByExample(@Param("record") SystemConfig record, @Param("example") SystemConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int updateByPrimaryKeySelective(SystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    int updateByPrimaryKey(SystemConfig record);
}