package me.anchora.inpaasmgr.dao.inpaasmgr;

import java.util.List;
import me.anchora.inpaasmgr.entry.inpaasmgr.UserBalances;
import me.anchora.inpaasmgr.entry.inpaasmgr.UserBalancesCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserBalancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int countByExample(UserBalancesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int deleteByExample(UserBalancesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int insert(UserBalances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int insertSelective(UserBalances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    List<UserBalances> selectByExampleWithRowbounds(UserBalancesCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    List<UserBalances> selectByExample(UserBalancesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    UserBalances selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserBalances record, @Param("example") UserBalancesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByExample(@Param("record") UserBalances record, @Param("example") UserBalancesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByPrimaryKeySelective(UserBalances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByPrimaryKey(UserBalances record);

	UserBalances queryByEmail(UserBalances userBalances);
}