package me.anchora.inpaasmgr.dao.inpaasmgr;

import java.util.List;
import me.anchora.inpaasmgr.entry.inpaasmgr.UserBalanceDetails;
import me.anchora.inpaasmgr.entry.inpaasmgr.UserBalanceDetailsCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserBalanceDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int countByExample(UserBalanceDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int deleteByExample(UserBalanceDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int insert(UserBalanceDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int insertSelective(UserBalanceDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    List<UserBalanceDetails> selectByExampleWithRowbounds(UserBalanceDetailsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    List<UserBalanceDetails> selectByExample(UserBalanceDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    UserBalanceDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserBalanceDetails record, @Param("example") UserBalanceDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByExample(@Param("record") UserBalanceDetails record, @Param("example") UserBalanceDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByPrimaryKeySelective(UserBalanceDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_details
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    int updateByPrimaryKey(UserBalanceDetails record);

	void createUserBalanceDetails();

	void insertUserBalanceDetails();
}