package me.anchora.inpaasmgr.entry.inpaasmgr;

import java.io.Serializable;
import java.util.Date;
import me.anchora.inpaasmgr.entry.base.PageEntry;

public class AppConfigs extends PageEntry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.id
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.app_guid
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private String appGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.app_name
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.is_autoscaling
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private String isAutoscaling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.autoscaling_type
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private String autoscalingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.autoscaling_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private Float autoscalingValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.autoscaling_trigger_type
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private String autoscalingTriggerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.autoscaling_trigger_up_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private Float autoscalingTriggerUpValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.autoscaling_trigger_down_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private Float autoscalingTriggerDownValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.remark
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.created_at
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.created_by
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.updated_at
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_configs.updated_by
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.id
     *
     * @return the value of app_configs.id
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.id
     *
     * @param id the value for app_configs.id
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.app_guid
     *
     * @return the value of app_configs.app_guid
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getAppGuid() {
        return appGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.app_guid
     *
     * @param appGuid the value for app_configs.app_guid
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setAppGuid(String appGuid) {
        this.appGuid = appGuid == null ? null : appGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.app_name
     *
     * @return the value of app_configs.app_name
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.app_name
     *
     * @param appName the value for app_configs.app_name
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.is_autoscaling
     *
     * @return the value of app_configs.is_autoscaling
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getIsAutoscaling() {
        return isAutoscaling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.is_autoscaling
     *
     * @param isAutoscaling the value for app_configs.is_autoscaling
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setIsAutoscaling(String isAutoscaling) {
        this.isAutoscaling = isAutoscaling == null ? null : isAutoscaling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.autoscaling_type
     *
     * @return the value of app_configs.autoscaling_type
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getAutoscalingType() {
        return autoscalingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.autoscaling_type
     *
     * @param autoscalingType the value for app_configs.autoscaling_type
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setAutoscalingType(String autoscalingType) {
        this.autoscalingType = autoscalingType == null ? null : autoscalingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.autoscaling_value
     *
     * @return the value of app_configs.autoscaling_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public Float getAutoscalingValue() {
        return autoscalingValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.autoscaling_value
     *
     * @param autoscalingValue the value for app_configs.autoscaling_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setAutoscalingValue(Float autoscalingValue) {
        this.autoscalingValue = autoscalingValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.autoscaling_trigger_type
     *
     * @return the value of app_configs.autoscaling_trigger_type
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getAutoscalingTriggerType() {
        return autoscalingTriggerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.autoscaling_trigger_type
     *
     * @param autoscalingTriggerType the value for app_configs.autoscaling_trigger_type
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setAutoscalingTriggerType(String autoscalingTriggerType) {
        this.autoscalingTriggerType = autoscalingTriggerType == null ? null : autoscalingTriggerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.autoscaling_trigger_up_value
     *
     * @return the value of app_configs.autoscaling_trigger_up_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public Float getAutoscalingTriggerUpValue() {
        return autoscalingTriggerUpValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.autoscaling_trigger_up_value
     *
     * @param autoscalingTriggerUpValue the value for app_configs.autoscaling_trigger_up_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setAutoscalingTriggerUpValue(Float autoscalingTriggerUpValue) {
        this.autoscalingTriggerUpValue = autoscalingTriggerUpValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.autoscaling_trigger_down_value
     *
     * @return the value of app_configs.autoscaling_trigger_down_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public Float getAutoscalingTriggerDownValue() {
        return autoscalingTriggerDownValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.autoscaling_trigger_down_value
     *
     * @param autoscalingTriggerDownValue the value for app_configs.autoscaling_trigger_down_value
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setAutoscalingTriggerDownValue(Float autoscalingTriggerDownValue) {
        this.autoscalingTriggerDownValue = autoscalingTriggerDownValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.remark
     *
     * @return the value of app_configs.remark
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.remark
     *
     * @param remark the value for app_configs.remark
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.created_at
     *
     * @return the value of app_configs.created_at
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.created_at
     *
     * @param createdAt the value for app_configs.created_at
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.created_by
     *
     * @return the value of app_configs.created_by
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.created_by
     *
     * @param createdBy the value for app_configs.created_by
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.updated_at
     *
     * @return the value of app_configs.updated_at
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.updated_at
     *
     * @param updatedAt the value for app_configs.updated_at
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_configs.updated_by
     *
     * @return the value of app_configs.updated_by
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_configs.updated_by
     *
     * @param updatedBy the value for app_configs.updated_by
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appGuid=").append(appGuid);
        sb.append(", appName=").append(appName);
        sb.append(", isAutoscaling=").append(isAutoscaling);
        sb.append(", autoscalingType=").append(autoscalingType);
        sb.append(", autoscalingValue=").append(autoscalingValue);
        sb.append(", autoscalingTriggerType=").append(autoscalingTriggerType);
        sb.append(", autoscalingTriggerUpValue=").append(autoscalingTriggerUpValue);
        sb.append(", autoscalingTriggerDownValue=").append(autoscalingTriggerDownValue);
        sb.append(", remark=").append(remark);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}