package me.anchora.inpaasmgr.entry.inpaasmgr;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppConfigsCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public AppConfigsCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppGuidIsNull() {
            addCriterion("app_guid is null");
            return (Criteria) this;
        }

        public Criteria andAppGuidIsNotNull() {
            addCriterion("app_guid is not null");
            return (Criteria) this;
        }

        public Criteria andAppGuidEqualTo(String value) {
            addCriterion("app_guid =", value, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidNotEqualTo(String value) {
            addCriterion("app_guid <>", value, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidGreaterThan(String value) {
            addCriterion("app_guid >", value, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidGreaterThanOrEqualTo(String value) {
            addCriterion("app_guid >=", value, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidLessThan(String value) {
            addCriterion("app_guid <", value, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidLessThanOrEqualTo(String value) {
            addCriterion("app_guid <=", value, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidLike(String value) {
            addCriterion("app_guid like", value, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidNotLike(String value) {
            addCriterion("app_guid not like", value, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidIn(List<String> values) {
            addCriterion("app_guid in", values, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidNotIn(List<String> values) {
            addCriterion("app_guid not in", values, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidBetween(String value1, String value2) {
            addCriterion("app_guid between", value1, value2, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppGuidNotBetween(String value1, String value2) {
            addCriterion("app_guid not between", value1, value2, "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNull() {
            addCriterion("app_name is null");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNotNull() {
            addCriterion("app_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppNameEqualTo(String value) {
            addCriterion("app_name =", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotEqualTo(String value) {
            addCriterion("app_name <>", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThan(String value) {
            addCriterion("app_name >", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_name >=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThan(String value) {
            addCriterion("app_name <", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThanOrEqualTo(String value) {
            addCriterion("app_name <=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLike(String value) {
            addCriterion("app_name like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotLike(String value) {
            addCriterion("app_name not like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameIn(List<String> values) {
            addCriterion("app_name in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotIn(List<String> values) {
            addCriterion("app_name not in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameBetween(String value1, String value2) {
            addCriterion("app_name between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotBetween(String value1, String value2) {
            addCriterion("app_name not between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingIsNull() {
            addCriterion("is_autoscaling is null");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingIsNotNull() {
            addCriterion("is_autoscaling is not null");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingEqualTo(String value) {
            addCriterion("is_autoscaling =", value, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingNotEqualTo(String value) {
            addCriterion("is_autoscaling <>", value, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingGreaterThan(String value) {
            addCriterion("is_autoscaling >", value, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingGreaterThanOrEqualTo(String value) {
            addCriterion("is_autoscaling >=", value, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingLessThan(String value) {
            addCriterion("is_autoscaling <", value, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingLessThanOrEqualTo(String value) {
            addCriterion("is_autoscaling <=", value, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingLike(String value) {
            addCriterion("is_autoscaling like", value, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingNotLike(String value) {
            addCriterion("is_autoscaling not like", value, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingIn(List<String> values) {
            addCriterion("is_autoscaling in", values, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingNotIn(List<String> values) {
            addCriterion("is_autoscaling not in", values, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingBetween(String value1, String value2) {
            addCriterion("is_autoscaling between", value1, value2, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingNotBetween(String value1, String value2) {
            addCriterion("is_autoscaling not between", value1, value2, "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeIsNull() {
            addCriterion("autoscaling_type is null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeIsNotNull() {
            addCriterion("autoscaling_type is not null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeEqualTo(String value) {
            addCriterion("autoscaling_type =", value, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeNotEqualTo(String value) {
            addCriterion("autoscaling_type <>", value, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeGreaterThan(String value) {
            addCriterion("autoscaling_type >", value, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("autoscaling_type >=", value, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeLessThan(String value) {
            addCriterion("autoscaling_type <", value, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeLessThanOrEqualTo(String value) {
            addCriterion("autoscaling_type <=", value, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeLike(String value) {
            addCriterion("autoscaling_type like", value, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeNotLike(String value) {
            addCriterion("autoscaling_type not like", value, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeIn(List<String> values) {
            addCriterion("autoscaling_type in", values, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeNotIn(List<String> values) {
            addCriterion("autoscaling_type not in", values, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeBetween(String value1, String value2) {
            addCriterion("autoscaling_type between", value1, value2, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeNotBetween(String value1, String value2) {
            addCriterion("autoscaling_type not between", value1, value2, "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueIsNull() {
            addCriterion("autoscaling_value is null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueIsNotNull() {
            addCriterion("autoscaling_value is not null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueEqualTo(Float value) {
            addCriterion("autoscaling_value =", value, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueNotEqualTo(Float value) {
            addCriterion("autoscaling_value <>", value, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueGreaterThan(Float value) {
            addCriterion("autoscaling_value >", value, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueGreaterThanOrEqualTo(Float value) {
            addCriterion("autoscaling_value >=", value, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueLessThan(Float value) {
            addCriterion("autoscaling_value <", value, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueLessThanOrEqualTo(Float value) {
            addCriterion("autoscaling_value <=", value, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueIn(List<Float> values) {
            addCriterion("autoscaling_value in", values, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueNotIn(List<Float> values) {
            addCriterion("autoscaling_value not in", values, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueBetween(Float value1, Float value2) {
            addCriterion("autoscaling_value between", value1, value2, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingValueNotBetween(Float value1, Float value2) {
            addCriterion("autoscaling_value not between", value1, value2, "autoscalingValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeIsNull() {
            addCriterion("autoscaling_trigger_type is null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeIsNotNull() {
            addCriterion("autoscaling_trigger_type is not null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeEqualTo(String value) {
            addCriterion("autoscaling_trigger_type =", value, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeNotEqualTo(String value) {
            addCriterion("autoscaling_trigger_type <>", value, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeGreaterThan(String value) {
            addCriterion("autoscaling_trigger_type >", value, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("autoscaling_trigger_type >=", value, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeLessThan(String value) {
            addCriterion("autoscaling_trigger_type <", value, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeLessThanOrEqualTo(String value) {
            addCriterion("autoscaling_trigger_type <=", value, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeLike(String value) {
            addCriterion("autoscaling_trigger_type like", value, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeNotLike(String value) {
            addCriterion("autoscaling_trigger_type not like", value, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeIn(List<String> values) {
            addCriterion("autoscaling_trigger_type in", values, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeNotIn(List<String> values) {
            addCriterion("autoscaling_trigger_type not in", values, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeBetween(String value1, String value2) {
            addCriterion("autoscaling_trigger_type between", value1, value2, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeNotBetween(String value1, String value2) {
            addCriterion("autoscaling_trigger_type not between", value1, value2, "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueIsNull() {
            addCriterion("autoscaling_trigger_up_value is null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueIsNotNull() {
            addCriterion("autoscaling_trigger_up_value is not null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueEqualTo(Float value) {
            addCriterion("autoscaling_trigger_up_value =", value, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueNotEqualTo(Float value) {
            addCriterion("autoscaling_trigger_up_value <>", value, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueGreaterThan(Float value) {
            addCriterion("autoscaling_trigger_up_value >", value, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueGreaterThanOrEqualTo(Float value) {
            addCriterion("autoscaling_trigger_up_value >=", value, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueLessThan(Float value) {
            addCriterion("autoscaling_trigger_up_value <", value, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueLessThanOrEqualTo(Float value) {
            addCriterion("autoscaling_trigger_up_value <=", value, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueIn(List<Float> values) {
            addCriterion("autoscaling_trigger_up_value in", values, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueNotIn(List<Float> values) {
            addCriterion("autoscaling_trigger_up_value not in", values, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueBetween(Float value1, Float value2) {
            addCriterion("autoscaling_trigger_up_value between", value1, value2, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerUpValueNotBetween(Float value1, Float value2) {
            addCriterion("autoscaling_trigger_up_value not between", value1, value2, "autoscalingTriggerUpValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueIsNull() {
            addCriterion("autoscaling_trigger_down_value is null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueIsNotNull() {
            addCriterion("autoscaling_trigger_down_value is not null");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueEqualTo(Float value) {
            addCriterion("autoscaling_trigger_down_value =", value, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueNotEqualTo(Float value) {
            addCriterion("autoscaling_trigger_down_value <>", value, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueGreaterThan(Float value) {
            addCriterion("autoscaling_trigger_down_value >", value, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueGreaterThanOrEqualTo(Float value) {
            addCriterion("autoscaling_trigger_down_value >=", value, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueLessThan(Float value) {
            addCriterion("autoscaling_trigger_down_value <", value, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueLessThanOrEqualTo(Float value) {
            addCriterion("autoscaling_trigger_down_value <=", value, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueIn(List<Float> values) {
            addCriterion("autoscaling_trigger_down_value in", values, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueNotIn(List<Float> values) {
            addCriterion("autoscaling_trigger_down_value not in", values, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueBetween(Float value1, Float value2) {
            addCriterion("autoscaling_trigger_down_value between", value1, value2, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerDownValueNotBetween(Float value1, Float value2) {
            addCriterion("autoscaling_trigger_down_value not between", value1, value2, "autoscalingTriggerDownValue");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andAppGuidLikeInsensitive(String value) {
            addCriterion("upper(app_guid) like", value.toUpperCase(), "appGuid");
            return (Criteria) this;
        }

        public Criteria andAppNameLikeInsensitive(String value) {
            addCriterion("upper(app_name) like", value.toUpperCase(), "appName");
            return (Criteria) this;
        }

        public Criteria andIsAutoscalingLikeInsensitive(String value) {
            addCriterion("upper(is_autoscaling) like", value.toUpperCase(), "isAutoscaling");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTypeLikeInsensitive(String value) {
            addCriterion("upper(autoscaling_type) like", value.toUpperCase(), "autoscalingType");
            return (Criteria) this;
        }

        public Criteria andAutoscalingTriggerTypeLikeInsensitive(String value) {
            addCriterion("upper(autoscaling_trigger_type) like", value.toUpperCase(), "autoscalingTriggerType");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }

        public Criteria andCreatedByLikeInsensitive(String value) {
            addCriterion("upper(created_by) like", value.toUpperCase(), "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLikeInsensitive(String value) {
            addCriterion("upper(updated_by) like", value.toUpperCase(), "updatedBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_configs
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 24 15:19:46 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_configs
     *
     * @mbggenerated Wed Dec 24 15:19:46 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}