package me.anchora.inpaasmgr.entry.inpaasmgr;

import java.io.Serializable;
import java.util.Date;

import me.anchora.inpaasmgr.entry.base.PageEntry;

public class AppLogAccessStatistics extends PageEntry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log_access_statistics.id
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log_access_statistics.app_guid
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    private String appGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log_access_statistics.flag
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    private Short flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log_access_statistics.log_date
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    private Date logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_log_access_statistics.log_count
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    private Long logCount;
    
    private String appName;
    
    private String appId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_log_access_statistics
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log_access_statistics.id
     *
     * @return the value of app_log_access_statistics.id
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log_access_statistics.id
     *
     * @param id the value for app_log_access_statistics.id
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log_access_statistics.app_guid
     *
     * @return the value of app_log_access_statistics.app_guid
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public String getAppGuid() {
        return appGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log_access_statistics.app_guid
     *
     * @param appGuid the value for app_log_access_statistics.app_guid
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public void setAppGuid(String appGuid) {
        this.appGuid = appGuid == null ? null : appGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log_access_statistics.flag
     *
     * @return the value of app_log_access_statistics.flag
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public Short getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log_access_statistics.flag
     *
     * @param flag the value for app_log_access_statistics.flag
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public void setFlag(Short flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log_access_statistics.log_date
     *
     * @return the value of app_log_access_statistics.log_date
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log_access_statistics.log_date
     *
     * @param logDate the value for app_log_access_statistics.log_date
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_log_access_statistics.log_count
     *
     * @return the value of app_log_access_statistics.log_count
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public Long getLogCount() {
        return logCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_log_access_statistics.log_count
     *
     * @param logCount the value for app_log_access_statistics.log_count
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    public void setLogCount(Long logCount) {
        this.logCount = logCount;
    }
    
    
    public String getAppName() {
        return appName;
    }
    public void setAppName(String appName) {
    	this.appName = appName;
	}
    
    
    
    public String getAppId() {
		return appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_log_access_statistics
     *
     * @mbggenerated Mon Mar 31 13:38:17 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appGuid=").append(appGuid);
        sb.append(", flag=").append(flag);
        sb.append(", logDate=").append(logDate);
        sb.append(", logCount=").append(logCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}