package me.anchora.inpaasmgr.entry.inpaasmgr;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CfMonitDatasCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public CfMonitDatasCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidIsNull() {
            addCriterion("cf_node_uuid is null");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidIsNotNull() {
            addCriterion("cf_node_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidEqualTo(String value) {
            addCriterion("cf_node_uuid =", value, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidNotEqualTo(String value) {
            addCriterion("cf_node_uuid <>", value, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidGreaterThan(String value) {
            addCriterion("cf_node_uuid >", value, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidGreaterThanOrEqualTo(String value) {
            addCriterion("cf_node_uuid >=", value, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidLessThan(String value) {
            addCriterion("cf_node_uuid <", value, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidLessThanOrEqualTo(String value) {
            addCriterion("cf_node_uuid <=", value, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidLike(String value) {
            addCriterion("cf_node_uuid like", value, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidNotLike(String value) {
            addCriterion("cf_node_uuid not like", value, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidIn(List<String> values) {
            addCriterion("cf_node_uuid in", values, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidNotIn(List<String> values) {
            addCriterion("cf_node_uuid not in", values, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidBetween(String value1, String value2) {
            addCriterion("cf_node_uuid between", value1, value2, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidNotBetween(String value1, String value2) {
            addCriterion("cf_node_uuid not between", value1, value2, "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameIsNull() {
            addCriterion("cf_node_name is null");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameIsNotNull() {
            addCriterion("cf_node_name is not null");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameEqualTo(String value) {
            addCriterion("cf_node_name =", value, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameNotEqualTo(String value) {
            addCriterion("cf_node_name <>", value, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameGreaterThan(String value) {
            addCriterion("cf_node_name >", value, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameGreaterThanOrEqualTo(String value) {
            addCriterion("cf_node_name >=", value, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameLessThan(String value) {
            addCriterion("cf_node_name <", value, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameLessThanOrEqualTo(String value) {
            addCriterion("cf_node_name <=", value, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameLike(String value) {
            addCriterion("cf_node_name like", value, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameNotLike(String value) {
            addCriterion("cf_node_name not like", value, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameIn(List<String> values) {
            addCriterion("cf_node_name in", values, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameNotIn(List<String> values) {
            addCriterion("cf_node_name not in", values, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameBetween(String value1, String value2) {
            addCriterion("cf_node_name between", value1, value2, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameNotBetween(String value1, String value2) {
            addCriterion("cf_node_name not between", value1, value2, "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpIsNull() {
            addCriterion("cf_node_ip is null");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpIsNotNull() {
            addCriterion("cf_node_ip is not null");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpEqualTo(String value) {
            addCriterion("cf_node_ip =", value, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpNotEqualTo(String value) {
            addCriterion("cf_node_ip <>", value, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpGreaterThan(String value) {
            addCriterion("cf_node_ip >", value, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpGreaterThanOrEqualTo(String value) {
            addCriterion("cf_node_ip >=", value, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpLessThan(String value) {
            addCriterion("cf_node_ip <", value, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpLessThanOrEqualTo(String value) {
            addCriterion("cf_node_ip <=", value, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpLike(String value) {
            addCriterion("cf_node_ip like", value, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpNotLike(String value) {
            addCriterion("cf_node_ip not like", value, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpIn(List<String> values) {
            addCriterion("cf_node_ip in", values, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpNotIn(List<String> values) {
            addCriterion("cf_node_ip not in", values, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpBetween(String value1, String value2) {
            addCriterion("cf_node_ip between", value1, value2, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpNotBetween(String value1, String value2) {
            addCriterion("cf_node_ip not between", value1, value2, "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeIsNull() {
            addCriterion("cf_node_uptime is null");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeIsNotNull() {
            addCriterion("cf_node_uptime is not null");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeEqualTo(String value) {
            addCriterion("cf_node_uptime =", value, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeNotEqualTo(String value) {
            addCriterion("cf_node_uptime <>", value, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeGreaterThan(String value) {
            addCriterion("cf_node_uptime >", value, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeGreaterThanOrEqualTo(String value) {
            addCriterion("cf_node_uptime >=", value, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeLessThan(String value) {
            addCriterion("cf_node_uptime <", value, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeLessThanOrEqualTo(String value) {
            addCriterion("cf_node_uptime <=", value, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeLike(String value) {
            addCriterion("cf_node_uptime like", value, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeNotLike(String value) {
            addCriterion("cf_node_uptime not like", value, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeIn(List<String> values) {
            addCriterion("cf_node_uptime in", values, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeNotIn(List<String> values) {
            addCriterion("cf_node_uptime not in", values, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeBetween(String value1, String value2) {
            addCriterion("cf_node_uptime between", value1, value2, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeNotBetween(String value1, String value2) {
            addCriterion("cf_node_uptime not between", value1, value2, "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andNumCoresIsNull() {
            addCriterion("num_cores is null");
            return (Criteria) this;
        }

        public Criteria andNumCoresIsNotNull() {
            addCriterion("num_cores is not null");
            return (Criteria) this;
        }

        public Criteria andNumCoresEqualTo(Float value) {
            addCriterion("num_cores =", value, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresNotEqualTo(Float value) {
            addCriterion("num_cores <>", value, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresGreaterThan(Float value) {
            addCriterion("num_cores >", value, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresGreaterThanOrEqualTo(Float value) {
            addCriterion("num_cores >=", value, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresLessThan(Float value) {
            addCriterion("num_cores <", value, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresLessThanOrEqualTo(Float value) {
            addCriterion("num_cores <=", value, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresIn(List<Float> values) {
            addCriterion("num_cores in", values, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresNotIn(List<Float> values) {
            addCriterion("num_cores not in", values, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresBetween(Float value1, Float value2) {
            addCriterion("num_cores between", value1, value2, "numCores");
            return (Criteria) this;
        }

        public Criteria andNumCoresNotBetween(Float value1, Float value2) {
            addCriterion("num_cores not between", value1, value2, "numCores");
            return (Criteria) this;
        }

        public Criteria andCpuIsNull() {
            addCriterion("cpu is null");
            return (Criteria) this;
        }

        public Criteria andCpuIsNotNull() {
            addCriterion("cpu is not null");
            return (Criteria) this;
        }

        public Criteria andCpuEqualTo(Float value) {
            addCriterion("cpu =", value, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuNotEqualTo(Float value) {
            addCriterion("cpu <>", value, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuGreaterThan(Float value) {
            addCriterion("cpu >", value, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuGreaterThanOrEqualTo(Float value) {
            addCriterion("cpu >=", value, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuLessThan(Float value) {
            addCriterion("cpu <", value, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuLessThanOrEqualTo(Float value) {
            addCriterion("cpu <=", value, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuIn(List<Float> values) {
            addCriterion("cpu in", values, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuNotIn(List<Float> values) {
            addCriterion("cpu not in", values, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuBetween(Float value1, Float value2) {
            addCriterion("cpu between", value1, value2, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuNotBetween(Float value1, Float value2) {
            addCriterion("cpu not between", value1, value2, "cpu");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgIsNull() {
            addCriterion("cpu_load_avg is null");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgIsNotNull() {
            addCriterion("cpu_load_avg is not null");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgEqualTo(Float value) {
            addCriterion("cpu_load_avg =", value, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgNotEqualTo(Float value) {
            addCriterion("cpu_load_avg <>", value, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgGreaterThan(Float value) {
            addCriterion("cpu_load_avg >", value, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgGreaterThanOrEqualTo(Float value) {
            addCriterion("cpu_load_avg >=", value, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgLessThan(Float value) {
            addCriterion("cpu_load_avg <", value, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgLessThanOrEqualTo(Float value) {
            addCriterion("cpu_load_avg <=", value, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgIn(List<Float> values) {
            addCriterion("cpu_load_avg in", values, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgNotIn(List<Float> values) {
            addCriterion("cpu_load_avg not in", values, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgBetween(Float value1, Float value2) {
            addCriterion("cpu_load_avg between", value1, value2, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andCpuLoadAvgNotBetween(Float value1, Float value2) {
            addCriterion("cpu_load_avg not between", value1, value2, "cpuLoadAvg");
            return (Criteria) this;
        }

        public Criteria andMemBytesIsNull() {
            addCriterion("mem_bytes is null");
            return (Criteria) this;
        }

        public Criteria andMemBytesIsNotNull() {
            addCriterion("mem_bytes is not null");
            return (Criteria) this;
        }

        public Criteria andMemBytesEqualTo(Float value) {
            addCriterion("mem_bytes =", value, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesNotEqualTo(Float value) {
            addCriterion("mem_bytes <>", value, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesGreaterThan(Float value) {
            addCriterion("mem_bytes >", value, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesGreaterThanOrEqualTo(Float value) {
            addCriterion("mem_bytes >=", value, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesLessThan(Float value) {
            addCriterion("mem_bytes <", value, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesLessThanOrEqualTo(Float value) {
            addCriterion("mem_bytes <=", value, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesIn(List<Float> values) {
            addCriterion("mem_bytes in", values, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesNotIn(List<Float> values) {
            addCriterion("mem_bytes not in", values, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesBetween(Float value1, Float value2) {
            addCriterion("mem_bytes between", value1, value2, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemBytesNotBetween(Float value1, Float value2) {
            addCriterion("mem_bytes not between", value1, value2, "memBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesIsNull() {
            addCriterion("mem_used_bytes is null");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesIsNotNull() {
            addCriterion("mem_used_bytes is not null");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesEqualTo(Float value) {
            addCriterion("mem_used_bytes =", value, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesNotEqualTo(Float value) {
            addCriterion("mem_used_bytes <>", value, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesGreaterThan(Float value) {
            addCriterion("mem_used_bytes >", value, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesGreaterThanOrEqualTo(Float value) {
            addCriterion("mem_used_bytes >=", value, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesLessThan(Float value) {
            addCriterion("mem_used_bytes <", value, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesLessThanOrEqualTo(Float value) {
            addCriterion("mem_used_bytes <=", value, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesIn(List<Float> values) {
            addCriterion("mem_used_bytes in", values, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesNotIn(List<Float> values) {
            addCriterion("mem_used_bytes not in", values, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesBetween(Float value1, Float value2) {
            addCriterion("mem_used_bytes between", value1, value2, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemUsedBytesNotBetween(Float value1, Float value2) {
            addCriterion("mem_used_bytes not between", value1, value2, "memUsedBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesIsNull() {
            addCriterion("mem_free_bytes is null");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesIsNotNull() {
            addCriterion("mem_free_bytes is not null");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesEqualTo(Float value) {
            addCriterion("mem_free_bytes =", value, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesNotEqualTo(Float value) {
            addCriterion("mem_free_bytes <>", value, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesGreaterThan(Float value) {
            addCriterion("mem_free_bytes >", value, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesGreaterThanOrEqualTo(Float value) {
            addCriterion("mem_free_bytes >=", value, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesLessThan(Float value) {
            addCriterion("mem_free_bytes <", value, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesLessThanOrEqualTo(Float value) {
            addCriterion("mem_free_bytes <=", value, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesIn(List<Float> values) {
            addCriterion("mem_free_bytes in", values, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesNotIn(List<Float> values) {
            addCriterion("mem_free_bytes not in", values, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesBetween(Float value1, Float value2) {
            addCriterion("mem_free_bytes between", value1, value2, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andMemFreeBytesNotBetween(Float value1, Float value2) {
            addCriterion("mem_free_bytes not between", value1, value2, "memFreeBytes");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioIsNull() {
            addCriterion("available_memory_ratio is null");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioIsNotNull() {
            addCriterion("available_memory_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioEqualTo(Float value) {
            addCriterion("available_memory_ratio =", value, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioNotEqualTo(Float value) {
            addCriterion("available_memory_ratio <>", value, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioGreaterThan(Float value) {
            addCriterion("available_memory_ratio >", value, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioGreaterThanOrEqualTo(Float value) {
            addCriterion("available_memory_ratio >=", value, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioLessThan(Float value) {
            addCriterion("available_memory_ratio <", value, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioLessThanOrEqualTo(Float value) {
            addCriterion("available_memory_ratio <=", value, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioIn(List<Float> values) {
            addCriterion("available_memory_ratio in", values, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioNotIn(List<Float> values) {
            addCriterion("available_memory_ratio not in", values, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioBetween(Float value1, Float value2) {
            addCriterion("available_memory_ratio between", value1, value2, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableMemoryRatioNotBetween(Float value1, Float value2) {
            addCriterion("available_memory_ratio not between", value1, value2, "availableMemoryRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioIsNull() {
            addCriterion("available_disk_ratio is null");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioIsNotNull() {
            addCriterion("available_disk_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioEqualTo(Float value) {
            addCriterion("available_disk_ratio =", value, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioNotEqualTo(Float value) {
            addCriterion("available_disk_ratio <>", value, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioGreaterThan(Float value) {
            addCriterion("available_disk_ratio >", value, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioGreaterThanOrEqualTo(Float value) {
            addCriterion("available_disk_ratio >=", value, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioLessThan(Float value) {
            addCriterion("available_disk_ratio <", value, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioLessThanOrEqualTo(Float value) {
            addCriterion("available_disk_ratio <=", value, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioIn(List<Float> values) {
            addCriterion("available_disk_ratio in", values, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioNotIn(List<Float> values) {
            addCriterion("available_disk_ratio not in", values, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioBetween(Float value1, Float value2) {
            addCriterion("available_disk_ratio between", value1, value2, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andAvailableDiskRatioNotBetween(Float value1, Float value2) {
            addCriterion("available_disk_ratio not between", value1, value2, "availableDiskRatio");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andCfNodeUuidLikeInsensitive(String value) {
            addCriterion("upper(cf_node_uuid) like", value.toUpperCase(), "cfNodeUuid");
            return (Criteria) this;
        }

        public Criteria andCfNodeNameLikeInsensitive(String value) {
            addCriterion("upper(cf_node_name) like", value.toUpperCase(), "cfNodeName");
            return (Criteria) this;
        }

        public Criteria andCfNodeIpLikeInsensitive(String value) {
            addCriterion("upper(cf_node_ip) like", value.toUpperCase(), "cfNodeIp");
            return (Criteria) this;
        }

        public Criteria andCfNodeUptimeLikeInsensitive(String value) {
            addCriterion("upper(cf_node_uptime) like", value.toUpperCase(), "cfNodeUptime");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }

        public Criteria andCreatedByLikeInsensitive(String value) {
            addCriterion("upper(created_by) like", value.toUpperCase(), "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLikeInsensitive(String value) {
            addCriterion("upper(updated_by) like", value.toUpperCase(), "updatedBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cf_monit_datas
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 25 14:45:34 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cf_monit_datas
     *
     * @mbggenerated Thu Dec 25 14:45:34 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}