package me.anchora.inpaasmgr.entry.inpaasmgr;

import java.io.Serializable;
import java.util.Date;

import me.anchora.inpaasmgr.entry.base.LoginSuper;

public class Login extends LoginSuper implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.user_name
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.level
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.locale
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String locale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.create_at
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.update_at
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.current_login
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private Date currentLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.last_login
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.timezone
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String timezone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.current_login_ip
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String currentLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.last_login_ip
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table login
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.user_name
     *
     * @return the value of login.user_name
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.user_name
     *
     * @param userName the value for login.user_name
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.level
     *
     * @return the value of login.level
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.level
     *
     * @param level the value for login.level
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.locale
     *
     * @return the value of login.locale
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.locale
     *
     * @param locale the value for login.locale
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setLocale(String locale) {
        this.locale = locale == null ? null : locale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.create_at
     *
     * @return the value of login.create_at
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.create_at
     *
     * @param createAt the value for login.create_at
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.update_at
     *
     * @return the value of login.update_at
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.update_at
     *
     * @param updateAt the value for login.update_at
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.current_login
     *
     * @return the value of login.current_login
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public Date getCurrentLogin() {
        return currentLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.current_login
     *
     * @param currentLogin the value for login.current_login
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setCurrentLogin(Date currentLogin) {
        this.currentLogin = currentLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.last_login
     *
     * @return the value of login.last_login
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.last_login
     *
     * @param lastLogin the value for login.last_login
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.timezone
     *
     * @return the value of login.timezone
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.timezone
     *
     * @param timezone the value for login.timezone
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setTimezone(String timezone) {
        this.timezone = timezone == null ? null : timezone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.current_login_ip
     *
     * @return the value of login.current_login_ip
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getCurrentLoginIp() {
        return currentLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.current_login_ip
     *
     * @param currentLoginIp the value for login.current_login_ip
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setCurrentLoginIp(String currentLoginIp) {
        this.currentLoginIp = currentLoginIp == null ? null : currentLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.last_login_ip
     *
     * @return the value of login.last_login_ip
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.last_login_ip
     *
     * @param lastLoginIp the value for login.last_login_ip
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", level=").append(level);
        sb.append(", locale=").append(locale);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", currentLogin=").append(currentLogin);
        sb.append(", lastLogin=").append(lastLogin);
        sb.append(", timezone=").append(timezone);
        sb.append(", currentLoginIp=").append(currentLoginIp);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}