package me.anchora.inpaasmgr.entry.inpaasmgr;

import java.io.Serializable;
import java.util.Date;
import me.anchora.inpaasmgr.entry.base.SuperMenus;

public class Menus extends SuperMenus implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.menu_name
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.parent_menu_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Long parentMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.menu_order
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Long menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.style_class
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String styleClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.menu_item_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String menuItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.remark
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.created_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.created_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.updated_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.updated_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menus
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.id
     *
     * @return the value of menus.id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.id
     *
     * @param id the value for menus.id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.menu_name
     *
     * @return the value of menus.menu_name
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.menu_name
     *
     * @param menuName the value for menus.menu_name
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.parent_menu_id
     *
     * @return the value of menus.parent_menu_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Long getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.parent_menu_id
     *
     * @param parentMenuId the value for menus.parent_menu_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setParentMenuId(Long parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.menu_order
     *
     * @return the value of menus.menu_order
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Long getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.menu_order
     *
     * @param menuOrder the value for menus.menu_order
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setMenuOrder(Long menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.style_class
     *
     * @return the value of menus.style_class
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getStyleClass() {
        return styleClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.style_class
     *
     * @param styleClass the value for menus.style_class
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setStyleClass(String styleClass) {
        this.styleClass = styleClass == null ? null : styleClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.menu_item_id
     *
     * @return the value of menus.menu_item_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getMenuItemId() {
        return menuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.menu_item_id
     *
     * @param menuItemId the value for menus.menu_item_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setMenuItemId(String menuItemId) {
        this.menuItemId = menuItemId == null ? null : menuItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.remark
     *
     * @return the value of menus.remark
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.remark
     *
     * @param remark the value for menus.remark
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.created_at
     *
     * @return the value of menus.created_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.created_at
     *
     * @param createdAt the value for menus.created_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.created_by
     *
     * @return the value of menus.created_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.created_by
     *
     * @param createdBy the value for menus.created_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.updated_at
     *
     * @return the value of menus.updated_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.updated_at
     *
     * @param updatedAt the value for menus.updated_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.updated_by
     *
     * @return the value of menus.updated_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.updated_by
     *
     * @param updatedBy the value for menus.updated_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", menuName=").append(menuName);
        sb.append(", parentMenuId=").append(parentMenuId);
        sb.append(", menuOrder=").append(menuOrder);
        sb.append(", styleClass=").append(styleClass);
        sb.append(", menuItemId=").append(menuItemId);
        sb.append(", remark=").append(remark);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}