package me.anchora.inpaasmgr.entry.inpaasmgr;

import java.io.Serializable;
import java.util.Date;

import me.anchora.inpaasmgr.entry.CommonVo2;

public class SystemConfig extends CommonVo2 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_name
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_value
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.remark
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.create_time
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.create_by
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.update_time
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.update_by
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.config_name
     *
     * @return the value of system_config.config_name
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.config_name
     *
     * @param configName the value for system_config.config_name
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.config_value
     *
     * @return the value of system_config.config_value
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.config_value
     *
     * @param configValue the value for system_config.config_value
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.remark
     *
     * @return the value of system_config.remark
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.remark
     *
     * @param remark the value for system_config.remark
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.create_time
     *
     * @return the value of system_config.create_time
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.create_time
     *
     * @param createTime the value for system_config.create_time
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.create_by
     *
     * @return the value of system_config.create_by
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.create_by
     *
     * @param createBy the value for system_config.create_by
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.update_time
     *
     * @return the value of system_config.update_time
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.update_time
     *
     * @param updateTime the value for system_config.update_time
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.update_by
     *
     * @return the value of system_config.update_by
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.update_by
     *
     * @param updateBy the value for system_config.update_by
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Mon Mar 09 15:18:43 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", configName=").append(configName);
        sb.append(", configValue=").append(configValue);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}