package me.anchora.inpaasmgr.entry.inpaasmgr;

import java.io.Serializable;
import java.util.Date;
import me.anchora.inpaasmgr.entry.base.PageEntry;

public class UserBalances extends PageEntry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.user_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.email
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.balance
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Float balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.balance_type
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String balanceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.remark
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.created_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.created_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.updated_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balances.updated_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.id
     *
     * @return the value of user_balances.id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.id
     *
     * @param id the value for user_balances.id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.user_id
     *
     * @return the value of user_balances.user_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.user_id
     *
     * @param userId the value for user_balances.user_id
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.email
     *
     * @return the value of user_balances.email
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.email
     *
     * @param email the value for user_balances.email
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.balance
     *
     * @return the value of user_balances.balance
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.balance
     *
     * @param balance the value for user_balances.balance
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.balance_type
     *
     * @return the value of user_balances.balance_type
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getBalanceType() {
        return balanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.balance_type
     *
     * @param balanceType the value for user_balances.balance_type
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setBalanceType(String balanceType) {
        this.balanceType = balanceType == null ? null : balanceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.remark
     *
     * @return the value of user_balances.remark
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.remark
     *
     * @param remark the value for user_balances.remark
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.created_at
     *
     * @return the value of user_balances.created_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.created_at
     *
     * @param createdAt the value for user_balances.created_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.created_by
     *
     * @return the value of user_balances.created_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.created_by
     *
     * @param createdBy the value for user_balances.created_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.updated_at
     *
     * @return the value of user_balances.updated_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.updated_at
     *
     * @param updatedAt the value for user_balances.updated_at
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balances.updated_by
     *
     * @return the value of user_balances.updated_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balances.updated_by
     *
     * @param updatedBy the value for user_balances.updated_by
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balances
     *
     * @mbggenerated Thu Mar 12 15:15:43 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", email=").append(email);
        sb.append(", balance=").append(balance);
        sb.append(", balanceType=").append(balanceType);
        sb.append(", remark=").append(remark);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}