package me.anchora.inpaasmgr.entry.uaadb;

import java.io.Serializable;
import java.util.Date;

import me.anchora.inpaasmgr.entry.CommonVo;

public class UaaUsers extends CommonVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.created
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.lastmodified
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Date lastmodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.version
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.username
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.password
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.email
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.authority
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Long authority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.givenname
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String givenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.familyname
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String familyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.active
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private Boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.phonenumber
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.authorities
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private String authorities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.id
     *
     * @return the value of public.users.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.id
     *
     * @param id the value for public.users.id
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.created
     *
     * @return the value of public.users.created
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.created
     *
     * @param created the value for public.users.created
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.lastmodified
     *
     * @return the value of public.users.lastmodified
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Date getLastmodified() {
        return lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.lastmodified
     *
     * @param lastmodified the value for public.users.lastmodified
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setLastmodified(Date lastmodified) {
        this.lastmodified = lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.version
     *
     * @return the value of public.users.version
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.version
     *
     * @param version the value for public.users.version
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.username
     *
     * @return the value of public.users.username
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.username
     *
     * @param username the value for public.users.username
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.password
     *
     * @return the value of public.users.password
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.password
     *
     * @param password the value for public.users.password
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.email
     *
     * @return the value of public.users.email
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.email
     *
     * @param email the value for public.users.email
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.authority
     *
     * @return the value of public.users.authority
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Long getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.authority
     *
     * @param authority the value for public.users.authority
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setAuthority(Long authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.givenname
     *
     * @return the value of public.users.givenname
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getGivenname() {
        return givenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.givenname
     *
     * @param givenname the value for public.users.givenname
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setGivenname(String givenname) {
        this.givenname = givenname == null ? null : givenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.familyname
     *
     * @return the value of public.users.familyname
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getFamilyname() {
        return familyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.familyname
     *
     * @param familyname the value for public.users.familyname
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setFamilyname(String familyname) {
        this.familyname = familyname == null ? null : familyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.active
     *
     * @return the value of public.users.active
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.active
     *
     * @param active the value for public.users.active
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.phonenumber
     *
     * @return the value of public.users.phonenumber
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.phonenumber
     *
     * @param phonenumber the value for public.users.phonenumber
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.authorities
     *
     * @return the value of public.users.authorities
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public String getAuthorities() {
        return authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.authorities
     *
     * @param authorities the value for public.users.authorities
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    public void setAuthorities(String authorities) {
        this.authorities = authorities == null ? null : authorities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Tue Mar 18 16:01:46 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", created=").append(created);
        sb.append(", lastmodified=").append(lastmodified);
        sb.append(", version=").append(version);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", authority=").append(authority);
        sb.append(", givenname=").append(givenname);
        sb.append(", familyname=").append(familyname);
        sb.append(", active=").append(active);
        sb.append(", phonenumber=").append(phonenumber);
        sb.append(", authorities=").append(authorities);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}