package me.anchora.inpaasmgr.dao.inpaas;

import java.util.List;
import me.anchora.inpaasmgr.entry.inpaas.PaasUsers;
import me.anchora.inpaasmgr.entry.inpaas.PaasUsersCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PaasUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int countByExample(PaasUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int deleteByExample(PaasUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int insert(PaasUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int insertSelective(PaasUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    List<PaasUsers> selectByExampleWithRowbounds(PaasUsersCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    List<PaasUsers> selectByExample(PaasUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    PaasUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") PaasUsers record, @Param("example") PaasUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int updateByExample(@Param("record") PaasUsers record, @Param("example") PaasUsersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int updateByPrimaryKeySelective(PaasUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_users
     *
     * @mbggenerated Tue Jun 09 10:16:48 CST 2015
     */
    int updateByPrimaryKey(PaasUsers record);
}